default:
  app:
    name: Account Service
    version: 1.0.0

  broker:
    amqp:
      exchange: headlessExchange
      username: rabbitmq
      password: rabbitmq
      host: localhost:15672
      port:
      topics: ["user.signup","user.login.#", "user.queue"]
      queue: user
      queueOptions:
        exclusive: false
        persistent: false
        durable: true
        autoDelete: false

development:

test:

staging:

production:
