default:
  app:
    name: Catalog Service
    version: 1.0.0

  broker:
    amqp:
      exchange: headlessExchange
      username: rabbitmq
      password: rabbitmq
      host: localhost:15672
      port:
      topics: ["catalog.product","catalog.products.#","catalog.add.#","catalog.update.#"]
      queue: catalog
      queueOptions:
        exclusive: false
        persistent: true
        durable: true
        autoDelete: true

development:

test:

staging:

production:
