default:
  app:
    name: Notification Service
    version: 1.0.0

  broker:
    amqp:
      exchange: headlessExchange
      username: rabbitmq
      password: rabbitmq
      host: localhost:15672
      port:
      topics: ["notify.welcome"]
      queue: notification
      queueOptions:
        exclusive: false
        persistent: true
        durable: true
        autoDelete: true

development:

test:

staging:

production:
