default:
  app:
    name: Order Service
    version: 1.0.0

  broker:
    amqp:
      exchange:
      username:
      password:
      host: localhost:15672
      port:
      topics: ["order.checkout","order.create.#"]
      queue: order.service.1.0.0
      queueOptions:
        exclusive: false
        durable: true
        autoDelete: true

development:

test:

staging:

production:
